import logging

from app.core.config import settings
from app.services.llm.base import LLMProvider
from app.services.llm.gemini import GeminiLLMProvider
from app.services.llm.mock import MockLLMProvider
from app.services.llm.openai import OpenAILLMProvider

logger = logging.getLogger(__name__)

SUPPORTED_LLM_PROVIDERS = {"mock", "openai", "gemini", "ollama"}


class LLMConfigurationError(RuntimeError):
    """Raised at startup when the LLM provider settings cannot work."""


def _configured_provider() -> str:
    return (settings.llm_provider or "mock").strip().lower()


def validate_llm_settings() -> None:
    """Fail fast on LLM settings that would otherwise silently fall back to mock output."""
    provider = _configured_provider()
    if provider not in SUPPORTED_LLM_PROVIDERS:
        raise LLMConfigurationError(
            f"알 수 없는 LLM_PROVIDER 값입니다: '{provider}'. mock, openai, gemini 중 하나로 설정하세요."
        )
    if provider == "openai" and not settings.openai_api_key:
        raise LLMConfigurationError(
            "LLM_PROVIDER=openai 이지만 OPENAI_API_KEY가 설정되지 않았습니다. 키를 설정하거나 LLM_PROVIDER=mock 으로 바꾸세요."
        )
    if provider == "gemini" and not settings.gemini_api_key:
        raise LLMConfigurationError(
            "LLM_PROVIDER=gemini 이지만 GEMINI_API_KEY가 설정되지 않았습니다. 키를 설정하거나 LLM_PROVIDER=mock 으로 바꾸세요."
        )
    if provider == "ollama":
        logger.warning("LLM_PROVIDER=ollama is not implemented yet; using the mock LLM provider.")
    elif provider == "mock":
        logger.warning("LLM_PROVIDER=mock; lecture notes will be generated by rule-based mock output.")


def effective_llm_provider_name() -> str:
    """The provider actually used for requests: "gemini", "openai" or "mock"."""
    provider = _configured_provider()
    if provider == "openai" and settings.openai_api_key:
        return "openai"
    if provider == "gemini" and settings.gemini_api_key:
        return "gemini"
    return "mock"


def effective_llm_model() -> str | None:
    name = effective_llm_provider_name()
    if name == "openai":
        return settings.openai_model
    if name == "gemini":
        return settings.gemini_model
    return None


def get_llm_provider() -> LLMProvider:
    name = effective_llm_provider_name()
    if name == "openai":
        return OpenAILLMProvider()
    if name == "gemini":
        return GeminiLLMProvider()
    return MockLLMProvider()
